In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_excel(r'C:\Users\nickm\Documents\candyhierarchy2017.xlsx')

In [7]:
df.head()

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"

In [8]:
df.shape

(2460, 120)

# Chapter 7

In [9]:
#filter out missing data
df.dropna(how='all')

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [13]:
#checking for duplicate ID's
df.drop_duplicates('Internal ID')

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(84, 25)"
2,90272829,NaN,Male,49,USA,Virginia,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,NaN,Raisins can go to hell,White and gold,NaN,Sunday,NaN,1.0,NaN,NaN,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,NaN,NaN,White and gold,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN,NaN,NaN,NaN
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,...,Capers,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,NaN,NaN,Blue and black,NaN,Friday,NaN,1.0,NaN,NaN,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,1.0,NaN,NaN,NaN,"(19, 26)"

In [10]:
#this would basically drop every row
df.dropna()

Empty DataFrame
Columns: [Internal ID, Q1: GOING OUT?, Q2: GENDER, Q3: AGE, Q4: COUNTRY, Q5: STATE, PROVINCE, COUNTY, ETC, Q6 | 100 Grand Bar, Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes), Q6 | Any full-sized candy bar, Q6 | Black Jacks, Q6 | Bonkers (the candy), Q6 | Bonkers (the board game), Q6 | Bottle Caps, Q6 | Box'o'Raisins, Q6 | Broken glow stick, Q6 | Butterfinger, Q6 | Cadbury Creme Eggs, Q6 | Candy Corn, Q6 | Candy that is clearly just the stuff given out for free at restaurants, Q6 | Caramellos, Q6 | Cash, or other forms of legal tender, Q6 | Chardonnay, Q6 | Chick-o-Sticks (we donâ€™t know what that is), Q6 | Chiclets, Q6 | Coffee Crisp, Q6 | Creepy Religious comics/Chick Tracts, Q6 | Dental paraphenalia, Q6 | Dots, Q6 | Dove Bars, Q6 | Fuzzy Peaches, Q6 | Generic Brand Acetaminophen, Q6 | Glow sticks, Q6 | Goo Goo Clusters, Q6 | Good N' Plenty, Q6 | Gum from baseball cards, Q6 | Gummy Bears straight up, Q6 | Hard Candy, Q6 | Healthy Fruit, Q6 | Heath Bar, Q6 | Hershey's Dark Chocolate, Q6 | Hersheyâ€™s Milk Chocolate, Q6 | Hershey's Kisses, Q6 | Hugs (actual physical hugs), Q6 | Jolly Rancher (bad flavor), Q6 | Jolly Ranchers (good flavor), Q6 | JoyJoy (Mit Iodine!), Q6 | Junior Mints, Q6 | Senior Mints, Q6 | Kale smoothie, Q6 | Kinder Happy Hippo, Q6 | Kit Kat, Q6 | LaffyTaffy, Q6 | LemonHeads, Q6 | Licorice (not black), Q6 | Licorice (yes black), Q6 | Lindt Truffle, Q6 | Lollipops, Q6 | Mars, Q6 | Maynards, Q6 | Mike and Ike, Q6 | Milk Duds, Q6 | Milky Way, Q6 | Regular M&Ms, Q6 | Peanut M&Mâ€™s, Q6 | Blue M&M's, Q6 | Red M&M's, Q6 | Green Party M&M's, Q6 | Independent M&M's, Q6 | Abstained from M&M'ing., Q6 | Minibags of chips, Q6 | Mint Kisses, Q6 | Mint Juleps, Q6 | Mr. Goodbar, Q6 | Necco Wafers, Q6 | Nerds, Q6 | Nestle Crunch, Q6 | Now'n'Laters, Q6 | Peeps, Q6 | Pencils, Q6 | Pixy Stix, Q6 | Real Housewives of Orange County Season 9 Blue-Ray, Q6 | Reeseâ€™s Peanut Butter Cups, Q6 | Reese's Pieces, Q6 | Reggie Jackson Bar, Q6 | Rolos, Q6 | Sandwich-sized bags filled with BooBerry Crunch, Q6 | Skittles, Q6 | Smarties (American), Q6 | Smarties (Commonwealth), Q6 | Snickers, Q6 | Sourpatch Kids (i.e. abominations of nature), Q6 | Spotted Dick, Q6 | Starburst, Q6 | Sweet Tarts, Q6 | Swedish Fish, Q6 | Sweetums (a friend to diabetes), Q6 | Take 5, Q6 | Tic Tacs, Q6 | Those odd marshmallow circus peanut things, Q6 | Three Musketeers, ...]
Index: []

[0 rows x 120 columns]

In [11]:
#Filling empty rows with "No response"
df.fillna('No reponse', inplace=True)

In [18]:
df

,Internal ID,Q1: GOING OUT?,Q2: GENDER,Q3: AGE,Q4: COUNTRY,"Q5: STATE, PROVINCE, COUNTY, ETC",Q6 | 100 Grand Bar,Q6 | Anonymous brown globs that come in black and orange wrappers\t(a.k.a. Mary Janes),Q6 | Any full-sized candy bar,Q6 | Black Jacks,...,Q8: DESPAIR OTHER,Q9: OTHER COMMENTS,Q10: DRESS,Unnamed: 113,Q11: DAY,Q12: MEDIA [Daily Dish],Q12: MEDIA [Science],Q12: MEDIA [ESPN],Q12: MEDIA [Yahoo],"Click Coordinates (x, y)"
0,90258773,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,No reponse,Bottom line is Twix is really the only candy w...,White and gold,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(84, 25)"
2,90272829,No reponse,Male,49,USA,Virginia,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,No reponse,Raisins can go to hell,White and gold,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,No reponse,No reponse,White and gold,No reponse,Friday,No reponse,1,No reponse,No reponse,"(70, 10)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,90314359,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,...,Fruit Stripe Gum,No reponse,White and gold,No reponse,Friday,No reponse,No reponse,No reponse,No reponse,No reponse
2456,90314580,No,Female,33,USA,New York,MEH,DESPAIR,JOY,No reponse,...,Capers,No reponse,Blue and black,No reponse,Friday,No reponse,1,No reponse,No reponse,"(70, 26)"
2457,90314634,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,...,No reponse,No reponse,Blue and black,No reponse,Friday,No reponse,1,No reponse,No reponse,"(67, 35)"
2458,90314658,No,Male,58,Usa,North Carolina,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
2459,90314802,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,...,No reponse,"You hit all my chocolate highlights, and broug...",White and gold,No reponse,Sunday,1,No reponse,No reponse,No reponse,"(19, 26)"

In [12]:
#Renaming columns. removing space and special characters
df.columns = ["Internal_ID",
"GOING_OUT",
"GENDER",
"AGE",
"COUNTRY",
"STATE",
"100_Grand_Bar",
"Anonymous_brown_globs_that_come_in_black_and_orange_wrappers",
"Any_fullsized_candy_bar",
"Black_Jacks",
"Bonkers_the_candy",
"Bonkers_the_board_game",
"Bottle_Caps",
"BoxoRaisins",
"Broken_glow_stick",
"Butterfinger",
"Cadbury_Creme_Eggs",
"Candy_Corn",
"Candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants",
"Caramellos",
"Cash_or_other_forms_of_legal_tender",
"Chardonnay",
"ChickoSticks_we_dont_know_what_that_is",
"Chiclets",
"Coffee_Crisp",
"Creepy_Religious_comics",
"Dental_paraphenalia",
"Dots",
"Dove_Bars",
"Fuzzy_Peaches",
"Generic_Brand_Acetaminophen",
"Glow_sticks",
"Goo_Goo_Clusters",
"Good_N_Plenty",
"Gum_from_baseball_cards",
"Gummy_Bears_straight_up",
"Hard_Candy",
"Healthy_Fruit",
"Heath_Bar",
"Hersheys_Dark_Chocolate",
"Hersheys_Milk_Chocolate",
"Hersheys_Kisses",
"Hugs_actual_physical_hugs",
"Jolly_Rancher_bad_flavor",
"Jolly_Ranchers_good_flavor",
"JoyJoy_Mit_Iodine",
"Junior_Mints",
"Senior_Mints",
"Kale_smoothie",
"Kinder_Happy_Hippo",
"Kit_Kat",
"LaffyTaffy",
"LemonHeads",
"Licorice_not_black",
"Licorice_yes_black",
"Lindt_Truffle",
"Lollipops",
"Mars",
"Maynards",
"Mike_and_Ike",
"Milk_Duds",
"Milky_Way",
"Regular_MMs",
"Peanut_MMs",
"Blue_MMs",
"Red_MMs",
"Green_Party_MMs",
"Independent_MMs",
"Abstained_from_MMing",
"Minibags_of_chips",
"Mint_Kisses",
"Mint_Juleps",
"Mr_Goodbar",
"Necco_Wafers",
"Nerds",
"Nestle_Crunch",
"NownLaters",
"Peeps",
"Pencils",
"Pixy_Stix",
"Real_Housewives_of_Orange_County_Season_9_BlueRay",
"Reeses_Peanut_Butter_Cups",
"Reeses_Pieces",
"Reggie_Jackson_Bar",
"Rolos",
"Sandwichsized_bags_filled_with_BooBerry_Crunch",
"Skittles",
"Smarties_American",
"Smarties_Commonwealth",
"Snickers",
"Sourpatch_Kids_ie_abominations_of_nature",
"Spotted_Dick",
"Starburst",
"Sweet_Tarts",
"Swedish_Fish",
"Sweetums_a_friend_to_diabetes",
"Take_5",
"Tic_Tacs",
"Those_odd_marshmallow_circus_peanut_things",
"Three_Musketeers",
"Tolberone_something_or_other",
"Trail_Mix",
"Twix",
"Vials_of_pure_high_fructose_corn_syrup_for_mainlining_into_your_vein",
"Vicodin",
"Whatchamacallit_Bars",
"White_Bread",
"Whole_Wheat_anything",
"York_Peppermint_Patties",
"JOY_OTHER",
"DESPAIR_OTHER",
"OTHER_COMMENTS",
"DRESS",
"Umpty",
"DAY",
"MEDIA_Daily_Dish",
"MEDIA_Science",
"MEDIA_ESPN",
"MEDIA_Yahoo",
"Click_Coordinates"
]

In [13]:
df.head(10)

,Internal_ID,GOING_OUT,GENDER,AGE,COUNTRY,STATE,100_Grand_Bar,Anonymous_brown_globs_that_come_in_black_and_orange_wrappers,Any_fullsized_candy_bar,Black_Jacks,...,DESPAIR_OTHER,OTHER_COMMENTS,DRESS,Umpty,DAY,MEDIA_Daily_Dish,MEDIA_Science,MEDIA_ESPN,MEDIA_Yahoo,Click_Coordinates
0,90258773,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
1,90272821,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,...,No reponse,Bottom line is Twix is really the only candy w...,White and gold,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(84, 25)"
2,90272829,No reponse,Male,49,USA,Virginia,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
3,90272840,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,...,No reponse,Raisins can go to hell,White and gold,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(75, 23)"
4,90272841,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,...,No reponse,No reponse,White and gold,No reponse,Friday,No reponse,1,No reponse,No reponse,"(70, 10)"
5,90272852,No,Male,No reponse,No reponse,No reponse,JOY,DESPAIR,JOY,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,1,No reponse,No reponse,"(75, 23)"
6,90272853,No,Male,53,usa,Colorado,No reponse,No reponse,No reponse,No reponse,...,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse,No reponse
7,90272854,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,No reponse,Friday,No reponse,1,No reponse,No reponse,"(55, 5)"
8,90272858,No,Male,40,Canada,Ontario,JOY,DESPAIR,JOY,MEH,...,No reponse,No reponse,Blue and black,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(76, 24)"
9,90272859,No,Female,53,Us,Wa,MEH,DESPAIR,JOY,MEH,...,No reponse,No reponse,White and gold,No reponse,Sunday,No reponse,1,No reponse,No reponse,"(70, 28)"

# chapter 8

In [24]:
#stack method to pivot data
results = df.stack()

In [37]:
results.shape

(295201,)

In [38]:
results.head(50)

0  Internal_ID                                                                 90258773
   GOING_OUT                                                                 No reponse
   GENDER                                                                    No reponse
   AGE                                                                       No reponse
   COUNTRY                                                                   No reponse
   STATE                                                                     No reponse
   100_Grand_Bar                                                             No reponse
   Anonymous_brown_globs_that_come_in_black_and_orange_wrappers              No reponse
   Any_fullsized_candy_bar                                                   No reponse
   Black_Jacks                                                               No reponse
   Bonkers_the_candy                                                         No reponse
   Bonkers_the_board_game                                                    No reponse
   Bottle_Caps                                                               No reponse
   BoxoRaisins                                                               No reponse
   Broken_glow_stick                                                         No reponse
   Butterfinger                                                              No reponse
   Cadbury_Creme_Eggs                                                        No reponse
   Candy_Corn                                                                No reponse
   Candy_that_is_clearly_just_the_stuff_given_out_for_free_at_restaurants    No reponse
   Caramellos                                                                No reponse
   Cash_or_other_forms_of_legal_tender                                       No reponse
   Chardonnay                                                                No reponse
   ChickoSticks_we_dont_know_what_that_is                                    No reponse
   Chiclets                                                                  No reponse
   Coffee_Crisp                                                              No reponse
   Creepy_Religious_comics                                                   No reponse
   Dental_paraphenalia                                                       No reponse
   Dots                                                                      No reponse
   Dove_Bars                                                                 No reponse
   Fuzzy_Peaches                                                             No reponse
   Generic_Brand_Acetaminophen                                               No reponse
   Glow_sticks                                                               No reponse
   Goo_Goo_Clusters                                                          No reponse
   Good_N_Plenty                                                             No reponse
   Gum_from_baseball_cards                                                   No reponse
   Gummy_Bears_straight_up                                                   No reponse
   Hard_Candy                                                                No reponse
   Healthy_Fruit                                                             No reponse
   Heath_Bar                                                                 No reponse
   Hersheys_Dark_Chocolate                                                   No reponse
   Hersheys_Milk_Chocolate                                                   No reponse
   Hersheys_Kisses                                                           No reponse
   Hugs_actual_physical_hugs                                                 No reponse
   Jolly_Rancher_bad_flavor                                                  No reponse
   Jolly_Ranchers_good_flavor                                                No reponse
   JoyJoy_Mit_Iodine                                                         No reponse
   Junior_Mints                                                              No reponse
   Senior_Mints                                                              No reponse
   Kale_smoothie                                                             No reponse
   Kinder_Happy_Hippo                                                        No reponse
dtype: object

# Chapter 10

In [30]:
#grouping by country
data_country= df.groupby(['COUNTRY'])['COUNTRY'].count()

In [33]:
#the country column is a mess lol
data_country.tail(40)

COUNTRY
United States                      37
United States of America           57
United States of America           11
United Statss                       1
United kingdom                      1
United staes                        1
United states                      19
United ststes                       1
Unites States                       4
Us                                 16
Usa                               139
Usa                                 1
america                             4
australia                           2
canada                             34
canada                              1
cascadia                            1
endland                             1
finland                             1
france                              1
germany                             3
hong kong                           1
insanity lately                     1
murrika                             1
soviet canuckistan                  1
spain                               1
subscribe to dm4uz3 on youtube      1
u s a                               1
u.s.                                3
u.s.a.                              1
uk                                  2
unhinged states                     1
unite states                        1
united States                       1
united states                      38
united states of america            5
united ststes                       1
us                                 40
usa                               217
usas                                1
Name: COUNTRY, dtype: int64

In [34]:
#Crosstabs
pd.crosstab(df.COUNTRY, df.GENDER, margins=True)

GENDER         Female  I'd rather not say  Male  No reponse  Other   All
COUNTRY
1                   0                   0     0           0      1     1
32                  0                   0     1           0      0     1
35                  1                   0     0           0      0     1
45                  1                   0     0           0      0     1
46                  0                   0     1           0      0     1
...               ...                 ...   ...         ...    ...   ...
united ststes       1                   0     0           0      0     1
us                 18                   3    19           0      0    40
usa                54                   6   156           1      0   217
usas                0                   1     0           0      0     1
All               839                  83  1467          41     30  2460

[130 rows x 6 columns]

# Chapter 11

In [35]:
df.DAY

0       No reponse
1           Sunday
2       No reponse
3           Sunday
4           Friday
           ...
2455        Friday
2456        Friday
2457        Friday
2458    No reponse
2459        Sunday
Name: DAY, Length: 2460, dtype: object

The data does not have any date time information. I was not sure how to create a time series analysis.